INSERT INTO clickhouse.dwh.dim_suppliers
WITH
    raw AS (
        SELECT
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM postgresql.public.mock_data
        UNION ALL
        SELECT
            CAST(id AS DECIMAL(38, 0)),
            CAST(customer_first_name AS VARCHAR),
            CAST(customer_last_name AS VARCHAR),
            CAST(customer_age AS DECIMAL(38, 0)),
            CAST(customer_email AS VARCHAR),
            CAST(customer_country AS VARCHAR),
            CAST(nullif(trim(CAST(customer_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(customer_pet_type AS VARCHAR),
            CAST(customer_pet_name AS VARCHAR),
            CAST(customer_pet_breed AS VARCHAR),
            CAST(seller_first_name AS VARCHAR),
            CAST(seller_last_name AS VARCHAR),
            CAST(seller_email AS VARCHAR),
            CAST(seller_country AS VARCHAR),
            CAST(nullif(trim(CAST(seller_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(product_name AS VARCHAR),
            CAST(product_category AS VARCHAR),
            CAST(product_price AS DECIMAL(38, 2)),
            CAST(product_quantity AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(sale_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(sale_customer_id AS DECIMAL(38, 0)),
            CAST(sale_seller_id AS DECIMAL(38, 0)),
            CAST(sale_product_id AS DECIMAL(38, 0)),
            CAST(sale_quantity AS DECIMAL(38, 0)),
            CAST(sale_total_price AS DECIMAL(38, 2)),
            CAST(store_name AS VARCHAR),
            CAST(store_location AS VARCHAR),
            CAST(store_city AS VARCHAR),
            CAST(nullif(trim(CAST(store_state AS VARCHAR)), '') AS VARCHAR),
            CAST(store_country AS VARCHAR),
            CAST(store_phone AS VARCHAR),
            CAST(store_email AS VARCHAR),
            CAST(pet_category AS VARCHAR),
            CAST(product_weight AS DECIMAL(38, 2)),
            CAST(product_color AS VARCHAR),
            CAST(product_size AS VARCHAR),
            CAST(product_brand AS VARCHAR),
            CAST(product_material AS VARCHAR),
            CAST(product_description AS VARCHAR),
            CAST(product_rating AS DECIMAL(38, 2)),
            CAST(product_reviews AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(product_release_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(date_parse(trim(CAST(product_expiry_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(supplier_name AS VARCHAR),
            CAST(supplier_contact AS VARCHAR),
            CAST(supplier_email AS VARCHAR),
            CAST(supplier_phone AS VARCHAR),
            CAST(supplier_address AS VARCHAR),
            CAST(supplier_city AS VARCHAR),
            CAST(supplier_country AS VARCHAR)
        FROM clickhouse.default.mock_data
    ),
    s AS (
        SELECT
            supplier_name,
            arbitrary(supplier_contact) AS supplier_contact,
            arbitrary(supplier_email) AS supplier_email,
            arbitrary(supplier_phone) AS supplier_phone,
            arbitrary(supplier_address) AS supplier_address,
            arbitrary(supplier_city) AS supplier_city,
            arbitrary(supplier_country) AS supplier_country
        FROM raw
        GROUP BY supplier_name
    )
SELECT
    row_number() OVER (ORDER BY supplier_name),
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM s;

INSERT INTO clickhouse.dwh.dim_stores
WITH
    raw AS (
        SELECT
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM postgresql.public.mock_data
        UNION ALL
        SELECT
            CAST(id AS DECIMAL(38, 0)),
            CAST(customer_first_name AS VARCHAR),
            CAST(customer_last_name AS VARCHAR),
            CAST(customer_age AS DECIMAL(38, 0)),
            CAST(customer_email AS VARCHAR),
            CAST(customer_country AS VARCHAR),
            CAST(nullif(trim(CAST(customer_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(customer_pet_type AS VARCHAR),
            CAST(customer_pet_name AS VARCHAR),
            CAST(customer_pet_breed AS VARCHAR),
            CAST(seller_first_name AS VARCHAR),
            CAST(seller_last_name AS VARCHAR),
            CAST(seller_email AS VARCHAR),
            CAST(seller_country AS VARCHAR),
            CAST(nullif(trim(CAST(seller_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(product_name AS VARCHAR),
            CAST(product_category AS VARCHAR),
            CAST(product_price AS DECIMAL(38, 2)),
            CAST(product_quantity AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(sale_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(sale_customer_id AS DECIMAL(38, 0)),
            CAST(sale_seller_id AS DECIMAL(38, 0)),
            CAST(sale_product_id AS DECIMAL(38, 0)),
            CAST(sale_quantity AS DECIMAL(38, 0)),
            CAST(sale_total_price AS DECIMAL(38, 2)),
            CAST(store_name AS VARCHAR),
            CAST(store_location AS VARCHAR),
            CAST(store_city AS VARCHAR),
            CAST(nullif(trim(CAST(store_state AS VARCHAR)), '') AS VARCHAR),
            CAST(store_country AS VARCHAR),
            CAST(store_phone AS VARCHAR),
            CAST(store_email AS VARCHAR),
            CAST(pet_category AS VARCHAR),
            CAST(product_weight AS DECIMAL(38, 2)),
            CAST(product_color AS VARCHAR),
            CAST(product_size AS VARCHAR),
            CAST(product_brand AS VARCHAR),
            CAST(product_material AS VARCHAR),
            CAST(product_description AS VARCHAR),
            CAST(product_rating AS DECIMAL(38, 2)),
            CAST(product_reviews AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(product_release_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(date_parse(trim(CAST(product_expiry_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(supplier_name AS VARCHAR),
            CAST(supplier_contact AS VARCHAR),
            CAST(supplier_email AS VARCHAR),
            CAST(supplier_phone AS VARCHAR),
            CAST(supplier_address AS VARCHAR),
            CAST(supplier_city AS VARCHAR),
            CAST(supplier_country AS VARCHAR)
        FROM clickhouse.default.mock_data
    ),
    st AS (
        SELECT
            store_name,
            arbitrary(store_location) AS store_location,
            arbitrary(store_city) AS store_city,
            arbitrary(store_state) AS store_state,
            arbitrary(store_country) AS store_country,
            arbitrary(store_phone) AS store_phone,
            arbitrary(store_email) AS store_email
        FROM raw
        GROUP BY store_name
    )
SELECT
    row_number() OVER (ORDER BY store_name),
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email
FROM st;

INSERT INTO clickhouse.dwh.dim_customers
WITH
    raw AS (
        SELECT
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM postgresql.public.mock_data
        UNION ALL
        SELECT
            CAST(id AS DECIMAL(38, 0)),
            CAST(customer_first_name AS VARCHAR),
            CAST(customer_last_name AS VARCHAR),
            CAST(customer_age AS DECIMAL(38, 0)),
            CAST(customer_email AS VARCHAR),
            CAST(customer_country AS VARCHAR),
            CAST(nullif(trim(CAST(customer_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(customer_pet_type AS VARCHAR),
            CAST(customer_pet_name AS VARCHAR),
            CAST(customer_pet_breed AS VARCHAR),
            CAST(seller_first_name AS VARCHAR),
            CAST(seller_last_name AS VARCHAR),
            CAST(seller_email AS VARCHAR),
            CAST(seller_country AS VARCHAR),
            CAST(nullif(trim(CAST(seller_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(product_name AS VARCHAR),
            CAST(product_category AS VARCHAR),
            CAST(product_price AS DECIMAL(38, 2)),
            CAST(product_quantity AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(sale_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(sale_customer_id AS DECIMAL(38, 0)),
            CAST(sale_seller_id AS DECIMAL(38, 0)),
            CAST(sale_product_id AS DECIMAL(38, 0)),
            CAST(sale_quantity AS DECIMAL(38, 0)),
            CAST(sale_total_price AS DECIMAL(38, 2)),
            CAST(store_name AS VARCHAR),
            CAST(store_location AS VARCHAR),
            CAST(store_city AS VARCHAR),
            CAST(nullif(trim(CAST(store_state AS VARCHAR)), '') AS VARCHAR),
            CAST(store_country AS VARCHAR),
            CAST(store_phone AS VARCHAR),
            CAST(store_email AS VARCHAR),
            CAST(pet_category AS VARCHAR),
            CAST(product_weight AS DECIMAL(38, 2)),
            CAST(product_color AS VARCHAR),
            CAST(product_size AS VARCHAR),
            CAST(product_brand AS VARCHAR),
            CAST(product_material AS VARCHAR),
            CAST(product_description AS VARCHAR),
            CAST(product_rating AS DECIMAL(38, 2)),
            CAST(product_reviews AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(product_release_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(date_parse(trim(CAST(product_expiry_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(supplier_name AS VARCHAR),
            CAST(supplier_contact AS VARCHAR),
            CAST(supplier_email AS VARCHAR),
            CAST(supplier_phone AS VARCHAR),
            CAST(supplier_address AS VARCHAR),
            CAST(supplier_city AS VARCHAR),
            CAST(supplier_country AS VARCHAR)
        FROM clickhouse.default.mock_data
    ),
    c AS (
        SELECT
            customer_email,
            arbitrary(customer_first_name) AS customer_first_name,
            arbitrary(customer_last_name) AS customer_last_name,
            arbitrary(customer_age) AS customer_age,
            arbitrary(customer_country) AS customer_country,
            arbitrary(customer_postal_code) AS customer_postal_code
        FROM raw
        GROUP BY customer_email
    )
SELECT
    row_number() OVER (ORDER BY customer_email),
    customer_first_name,
    customer_last_name,
    customer_email,
    CAST(round(customer_age) AS INTEGER),
    customer_country,
    customer_postal_code
FROM c;

INSERT INTO clickhouse.dwh.dim_sellers
WITH
    raw AS (
        SELECT
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM postgresql.public.mock_data
        UNION ALL
        SELECT
            CAST(id AS DECIMAL(38, 0)),
            CAST(customer_first_name AS VARCHAR),
            CAST(customer_last_name AS VARCHAR),
            CAST(customer_age AS DECIMAL(38, 0)),
            CAST(customer_email AS VARCHAR),
            CAST(customer_country AS VARCHAR),
            CAST(nullif(trim(CAST(customer_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(customer_pet_type AS VARCHAR),
            CAST(customer_pet_name AS VARCHAR),
            CAST(customer_pet_breed AS VARCHAR),
            CAST(seller_first_name AS VARCHAR),
            CAST(seller_last_name AS VARCHAR),
            CAST(seller_email AS VARCHAR),
            CAST(seller_country AS VARCHAR),
            CAST(nullif(trim(CAST(seller_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(product_name AS VARCHAR),
            CAST(product_category AS VARCHAR),
            CAST(product_price AS DECIMAL(38, 2)),
            CAST(product_quantity AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(sale_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(sale_customer_id AS DECIMAL(38, 0)),
            CAST(sale_seller_id AS DECIMAL(38, 0)),
            CAST(sale_product_id AS DECIMAL(38, 0)),
            CAST(sale_quantity AS DECIMAL(38, 0)),
            CAST(sale_total_price AS DECIMAL(38, 2)),
            CAST(store_name AS VARCHAR),
            CAST(store_location AS VARCHAR),
            CAST(store_city AS VARCHAR),
            CAST(nullif(trim(CAST(store_state AS VARCHAR)), '') AS VARCHAR),
            CAST(store_country AS VARCHAR),
            CAST(store_phone AS VARCHAR),
            CAST(store_email AS VARCHAR),
            CAST(pet_category AS VARCHAR),
            CAST(product_weight AS DECIMAL(38, 2)),
            CAST(product_color AS VARCHAR),
            CAST(product_size AS VARCHAR),
            CAST(product_brand AS VARCHAR),
            CAST(product_material AS VARCHAR),
            CAST(product_description AS VARCHAR),
            CAST(product_rating AS DECIMAL(38, 2)),
            CAST(product_reviews AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(product_release_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(date_parse(trim(CAST(product_expiry_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(supplier_name AS VARCHAR),
            CAST(supplier_contact AS VARCHAR),
            CAST(supplier_email AS VARCHAR),
            CAST(supplier_phone AS VARCHAR),
            CAST(supplier_address AS VARCHAR),
            CAST(supplier_city AS VARCHAR),
            CAST(supplier_country AS VARCHAR)
        FROM clickhouse.default.mock_data
    ),
    j AS (
        SELECT
            r.seller_first_name,
            r.seller_last_name,
            r.seller_email,
            s.store_id
        FROM raw r
        INNER JOIN clickhouse.dwh.dim_stores s ON r.store_name = s.store_name
    ),
    sel AS (
        SELECT
            seller_email,
            arbitrary(seller_first_name) AS seller_first_name,
            arbitrary(seller_last_name) AS seller_last_name,
            arbitrary(store_id) AS store_id
        FROM j
        GROUP BY seller_email
    )
SELECT
    row_number() OVER (ORDER BY seller_email),
    seller_first_name,
    seller_last_name,
    seller_email,
    store_id
FROM sel;

INSERT INTO clickhouse.dwh.dim_products
WITH
    raw AS (
        SELECT
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM postgresql.public.mock_data
        UNION ALL
        SELECT
            CAST(id AS DECIMAL(38, 0)),
            CAST(customer_first_name AS VARCHAR),
            CAST(customer_last_name AS VARCHAR),
            CAST(customer_age AS DECIMAL(38, 0)),
            CAST(customer_email AS VARCHAR),
            CAST(customer_country AS VARCHAR),
            CAST(nullif(trim(CAST(customer_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(customer_pet_type AS VARCHAR),
            CAST(customer_pet_name AS VARCHAR),
            CAST(customer_pet_breed AS VARCHAR),
            CAST(seller_first_name AS VARCHAR),
            CAST(seller_last_name AS VARCHAR),
            CAST(seller_email AS VARCHAR),
            CAST(seller_country AS VARCHAR),
            CAST(nullif(trim(CAST(seller_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(product_name AS VARCHAR),
            CAST(product_category AS VARCHAR),
            CAST(product_price AS DECIMAL(38, 2)),
            CAST(product_quantity AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(sale_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(sale_customer_id AS DECIMAL(38, 0)),
            CAST(sale_seller_id AS DECIMAL(38, 0)),
            CAST(sale_product_id AS DECIMAL(38, 0)),
            CAST(sale_quantity AS DECIMAL(38, 0)),
            CAST(sale_total_price AS DECIMAL(38, 2)),
            CAST(store_name AS VARCHAR),
            CAST(store_location AS VARCHAR),
            CAST(store_city AS VARCHAR),
            CAST(nullif(trim(CAST(store_state AS VARCHAR)), '') AS VARCHAR),
            CAST(store_country AS VARCHAR),
            CAST(store_phone AS VARCHAR),
            CAST(store_email AS VARCHAR),
            CAST(pet_category AS VARCHAR),
            CAST(product_weight AS DECIMAL(38, 2)),
            CAST(product_color AS VARCHAR),
            CAST(product_size AS VARCHAR),
            CAST(product_brand AS VARCHAR),
            CAST(product_material AS VARCHAR),
            CAST(product_description AS VARCHAR),
            CAST(product_rating AS DECIMAL(38, 2)),
            CAST(product_reviews AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(product_release_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(date_parse(trim(CAST(product_expiry_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(supplier_name AS VARCHAR),
            CAST(supplier_contact AS VARCHAR),
            CAST(supplier_email AS VARCHAR),
            CAST(supplier_phone AS VARCHAR),
            CAST(supplier_address AS VARCHAR),
            CAST(supplier_city AS VARCHAR),
            CAST(supplier_country AS VARCHAR)
        FROM clickhouse.default.mock_data
    ),
    j AS (
        SELECT
            r.product_name,
            r.product_category,
            r.product_brand,
            r.product_price,
            sup.supplier_id
        FROM raw r
        INNER JOIN clickhouse.dwh.dim_suppliers sup ON r.supplier_name = sup.supplier_name
    ),
    p AS (
        SELECT
            product_name,
            arbitrary(product_category) AS product_category,
            arbitrary(product_brand) AS product_brand,
            arbitrary(product_price) AS product_price,
            arbitrary(supplier_id) AS supplier_id
        FROM j
        GROUP BY product_name
    )
SELECT
    row_number() OVER (ORDER BY product_name),
    product_name,
    product_category,
    product_brand,
    CAST(round(product_price, 2) AS DECIMAL(18, 2)),
    supplier_id
FROM p;

INSERT INTO clickhouse.dwh.dim_pets
WITH
    raw AS (
        SELECT
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM postgresql.public.mock_data
        UNION ALL
        SELECT
            CAST(id AS DECIMAL(38, 0)),
            CAST(customer_first_name AS VARCHAR),
            CAST(customer_last_name AS VARCHAR),
            CAST(customer_age AS DECIMAL(38, 0)),
            CAST(customer_email AS VARCHAR),
            CAST(customer_country AS VARCHAR),
            CAST(nullif(trim(CAST(customer_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(customer_pet_type AS VARCHAR),
            CAST(customer_pet_name AS VARCHAR),
            CAST(customer_pet_breed AS VARCHAR),
            CAST(seller_first_name AS VARCHAR),
            CAST(seller_last_name AS VARCHAR),
            CAST(seller_email AS VARCHAR),
            CAST(seller_country AS VARCHAR),
            CAST(nullif(trim(CAST(seller_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(product_name AS VARCHAR),
            CAST(product_category AS VARCHAR),
            CAST(product_price AS DECIMAL(38, 2)),
            CAST(product_quantity AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(sale_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(sale_customer_id AS DECIMAL(38, 0)),
            CAST(sale_seller_id AS DECIMAL(38, 0)),
            CAST(sale_product_id AS DECIMAL(38, 0)),
            CAST(sale_quantity AS DECIMAL(38, 0)),
            CAST(sale_total_price AS DECIMAL(38, 2)),
            CAST(store_name AS VARCHAR),
            CAST(store_location AS VARCHAR),
            CAST(store_city AS VARCHAR),
            CAST(nullif(trim(CAST(store_state AS VARCHAR)), '') AS VARCHAR),
            CAST(store_country AS VARCHAR),
            CAST(store_phone AS VARCHAR),
            CAST(store_email AS VARCHAR),
            CAST(pet_category AS VARCHAR),
            CAST(product_weight AS DECIMAL(38, 2)),
            CAST(product_color AS VARCHAR),
            CAST(product_size AS VARCHAR),
            CAST(product_brand AS VARCHAR),
            CAST(product_material AS VARCHAR),
            CAST(product_description AS VARCHAR),
            CAST(product_rating AS DECIMAL(38, 2)),
            CAST(product_reviews AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(product_release_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(date_parse(trim(CAST(product_expiry_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(supplier_name AS VARCHAR),
            CAST(supplier_contact AS VARCHAR),
            CAST(supplier_email AS VARCHAR),
            CAST(supplier_phone AS VARCHAR),
            CAST(supplier_address AS VARCHAR),
            CAST(supplier_city AS VARCHAR),
            CAST(supplier_country AS VARCHAR)
        FROM clickhouse.default.mock_data
    ),
    pe AS (
        SELECT
            r.customer_pet_name AS pet_name,
            arbitrary(r.customer_pet_type) AS pet_type,
            arbitrary(r.customer_pet_breed) AS pet_breed,
            c.customer_id
        FROM raw r
        INNER JOIN clickhouse.dwh.dim_customers c ON r.customer_email = c.customer_email
        GROUP BY r.customer_pet_name, c.customer_id
    )
SELECT
    row_number() OVER (ORDER BY customer_id, pet_name),
    pet_name,
    pet_type,
    pet_breed,
    customer_id
FROM pe;

INSERT INTO clickhouse.dwh.fact_sales
WITH
    raw AS (
        SELECT
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM postgresql.public.mock_data
        UNION ALL
        SELECT
            CAST(id AS DECIMAL(38, 0)),
            CAST(customer_first_name AS VARCHAR),
            CAST(customer_last_name AS VARCHAR),
            CAST(customer_age AS DECIMAL(38, 0)),
            CAST(customer_email AS VARCHAR),
            CAST(customer_country AS VARCHAR),
            CAST(nullif(trim(CAST(customer_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(customer_pet_type AS VARCHAR),
            CAST(customer_pet_name AS VARCHAR),
            CAST(customer_pet_breed AS VARCHAR),
            CAST(seller_first_name AS VARCHAR),
            CAST(seller_last_name AS VARCHAR),
            CAST(seller_email AS VARCHAR),
            CAST(seller_country AS VARCHAR),
            CAST(nullif(trim(CAST(seller_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(product_name AS VARCHAR),
            CAST(product_category AS VARCHAR),
            CAST(product_price AS DECIMAL(38, 2)),
            CAST(product_quantity AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(sale_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(sale_customer_id AS DECIMAL(38, 0)),
            CAST(sale_seller_id AS DECIMAL(38, 0)),
            CAST(sale_product_id AS DECIMAL(38, 0)),
            CAST(sale_quantity AS DECIMAL(38, 0)),
            CAST(sale_total_price AS DECIMAL(38, 2)),
            CAST(store_name AS VARCHAR),
            CAST(store_location AS VARCHAR),
            CAST(store_city AS VARCHAR),
            CAST(nullif(trim(CAST(store_state AS VARCHAR)), '') AS VARCHAR),
            CAST(store_country AS VARCHAR),
            CAST(store_phone AS VARCHAR),
            CAST(store_email AS VARCHAR),
            CAST(pet_category AS VARCHAR),
            CAST(product_weight AS DECIMAL(38, 2)),
            CAST(product_color AS VARCHAR),
            CAST(product_size AS VARCHAR),
            CAST(product_brand AS VARCHAR),
            CAST(product_material AS VARCHAR),
            CAST(product_description AS VARCHAR),
            CAST(product_rating AS DECIMAL(38, 2)),
            CAST(product_reviews AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(product_release_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(date_parse(trim(CAST(product_expiry_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(supplier_name AS VARCHAR),
            CAST(supplier_contact AS VARCHAR),
            CAST(supplier_email AS VARCHAR),
            CAST(supplier_phone AS VARCHAR),
            CAST(supplier_address AS VARCHAR),
            CAST(supplier_city AS VARCHAR),
            CAST(supplier_country AS VARCHAR)
        FROM clickhouse.default.mock_data
    ),
    f AS (
        SELECT
            r.sale_date,
            c.customer_id,
            sel.seller_id,
            p.product_id,
            st.store_id,
            CAST(round(r.sale_quantity) AS INTEGER) AS quantity,
            CAST(round(r.sale_total_price, 2) AS DECIMAL(18, 2)) AS total_price,
            row_number() OVER (
                ORDER BY
                    r.sale_date,
                    c.customer_id,
                    p.product_id,
                    st.store_id,
                    r.sale_total_price
            ) AS sale_id
        FROM raw r
        INNER JOIN clickhouse.dwh.dim_customers c ON r.customer_email = c.customer_email
        INNER JOIN clickhouse.dwh.dim_sellers sel ON r.seller_email = sel.seller_email
        INNER JOIN clickhouse.dwh.dim_products p ON r.product_name = p.product_name
        INNER JOIN clickhouse.dwh.dim_stores st ON r.store_name = st.store_name
    )
SELECT sale_id, sale_date, customer_id, seller_id, product_id, store_id, quantity, total_price
FROM f;

-- Денормализованный UNION сырых строк для витрин (рейтинги, отзывы без повторного UNION в скрипте отчётов).
DROP TABLE IF EXISTS clickhouse.dwh.stg_raw_union;

CREATE TABLE clickhouse.dwh.stg_raw_union AS
WITH
    raw AS (
        SELECT
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM postgresql.public.mock_data
        UNION ALL
        SELECT
            CAST(id AS DECIMAL(38, 0)),
            CAST(customer_first_name AS VARCHAR),
            CAST(customer_last_name AS VARCHAR),
            CAST(customer_age AS DECIMAL(38, 0)),
            CAST(customer_email AS VARCHAR),
            CAST(customer_country AS VARCHAR),
            CAST(nullif(trim(CAST(customer_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(customer_pet_type AS VARCHAR),
            CAST(customer_pet_name AS VARCHAR),
            CAST(customer_pet_breed AS VARCHAR),
            CAST(seller_first_name AS VARCHAR),
            CAST(seller_last_name AS VARCHAR),
            CAST(seller_email AS VARCHAR),
            CAST(seller_country AS VARCHAR),
            CAST(nullif(trim(CAST(seller_postal_code AS VARCHAR)), '') AS VARCHAR),
            CAST(product_name AS VARCHAR),
            CAST(product_category AS VARCHAR),
            CAST(product_price AS DECIMAL(38, 2)),
            CAST(product_quantity AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(sale_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(sale_customer_id AS DECIMAL(38, 0)),
            CAST(sale_seller_id AS DECIMAL(38, 0)),
            CAST(sale_product_id AS DECIMAL(38, 0)),
            CAST(sale_quantity AS DECIMAL(38, 0)),
            CAST(sale_total_price AS DECIMAL(38, 2)),
            CAST(store_name AS VARCHAR),
            CAST(store_location AS VARCHAR),
            CAST(store_city AS VARCHAR),
            CAST(nullif(trim(CAST(store_state AS VARCHAR)), '') AS VARCHAR),
            CAST(store_country AS VARCHAR),
            CAST(store_phone AS VARCHAR),
            CAST(store_email AS VARCHAR),
            CAST(pet_category AS VARCHAR),
            CAST(product_weight AS DECIMAL(38, 2)),
            CAST(product_color AS VARCHAR),
            CAST(product_size AS VARCHAR),
            CAST(product_brand AS VARCHAR),
            CAST(product_material AS VARCHAR),
            CAST(product_description AS VARCHAR),
            CAST(product_rating AS DECIMAL(38, 2)),
            CAST(product_reviews AS DECIMAL(38, 0)),
            CAST(date_parse(trim(CAST(product_release_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(date_parse(trim(CAST(product_expiry_date AS VARCHAR)), '%m/%d/%Y') AS DATE),
            CAST(supplier_name AS VARCHAR),
            CAST(supplier_contact AS VARCHAR),
            CAST(supplier_email AS VARCHAR),
            CAST(supplier_phone AS VARCHAR),
            CAST(supplier_address AS VARCHAR),
            CAST(supplier_city AS VARCHAR),
            CAST(supplier_country AS VARCHAR)
        FROM clickhouse.default.mock_data
    )
SELECT * FROM raw;
